### ISSUE TITLE
iOS min deployment target

### ISSUE THREAD

**Issue by acerbetti** [relatedcode/RCMessageKit#6]
Hi, thanks for your library. One question:

why do you state in the readme to be compatible with iOS 9.3+, but in the PodSpec you are set for iOS11. 

Thanks again

**Comment by relatedcode** [comment]
@acerbetti Sorry, it's my mistake. The library is now iOS 11+

**Comment by JiaLiangoooo** [comment]
Can I use it on iOS 9?
